version: '3.8'
services:
  redis:
    image: redis:6
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data